article/urls.py
# 简单来说就是Model存取数据，View决定需要调取哪些数据，而Template则负责将调取出的数据以合理的方式展现出来。

# 引入path
from django.urls import path
from article import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 安全删除文章
    # path('article-delete/<int:id>', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>', views.article_safe_delete, name='article_safe_delete'),
    # 更新文章
    path('article-updatee/<int:id>/', views.article_updatee, name='article_updatee'),
    #类视图新建文章
    path('create-view/', views.ArticleCreateView.as_view(), name='...'),
    #点赞 +1
    path('increase-likes/<int:id>', views.IncreaseLikesView.as_view(), name='increase_likes'),

]

my_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
#记得引入include
from django.urls import path, include
import notifications.urls

from article.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),

    #新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    #用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    #第三方库：密码重置
    path('password-reset/', include('password_reset.urls')),
    #评论
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('accounts/', include('allauth.urls')),
    #home
    path('', article_list, name='home'),
]

#添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
#! usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2021/12/29 17:29
# @Author: wangjunjie
# @File: urls.py
# @Des:

from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    #用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    //向上滚动的函数
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
            });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
<!--
    载入静态文件
    使用Django 3 学习的读者改为 {% load static %}
-->
{% load staticfiles %}

<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">

    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

    <!-- 引入矢量图标文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css">
</head>
<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}

<!-- 新增两个div容器 -->
<div id="wrapper">
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content%}
</div>

<!-- 引入注脚 -->
{% include 'footer.html' %}
<!-- bootstrap.js 依赖jquery.js和popper.js，因此在这里引入-->
<script src="{% static 'jquery/jquery-3.6.0.js'%}"></script>
<!-- 新增代码 -->
{% block script %}{% endblock script %}
<!-- 在jquery后面引入 -->
{% include 'back_to_top_func.html' %}
<!-- 引入layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>
<!--
    popper.js采用cdn远程引入，意思是你不需要把它下载到本地。
    在实际的开发中推荐静态文件尽量都使用cdn的形式。
    教程采用本地引入是为了让读者了解静态文件本地部署的流程。
-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.js"></script>

<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
 <!-- 增加样式 -->
<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    #wrapper {
        min-height: 100%;
        margin-bottom: -60px;
    }

    #footer,
    #push {
        height: 60px;
    }
</style>
</body>
</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<!-- 删除了 fixed-bottom属性 -->
<!-- 增加 id="footer"属性 -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.cnblogs.com/wangjunjiehome/ 2022</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏图标 -->
        <a class="navbar-brand" href="{% url 'article:article_list' %}">我的博客</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    <!-- 改写了这里的href -->
                    <!-- 通过这样的方法就将链接跳转的指向给配置好了，只要对应url的名称不变，url本身无论怎么变化，Django都可以解析到正确的地址，很灵活。
                         当然你也可以直接在href中写入url的地址，但是一旦url有变化，所有相关的链接都会失效，维护性不好。 -->
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>

                <!-- Django的if模板语句 -->
                {% if user.is_authenticated %}
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <!-- 新增 -->
                        <a class="dropdown-item" href="{% url 'userprofile:edit' user.id %}">个人信息</a>
                        <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                        <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示”登录“ -->
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                </li>
                <!-- if 语句在这里结束 -->
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- 新增删除用户弹窗 -->
{% if user.is_authenticated %}
<form
        style="display: none;"
        id="user_delete"
        action="{% url 'userprofile:delete' user.id %}"
        method="POST">
    {% csrf_token %}
    <button type="submit">发送</button>
</form>
<script>
    function user_delete() {
        //调用layer弹窗组件
        layer.open({
            title: "确认删除",
            content: "确认删除用户资料吗？",
            yes: function (index, layero) {
                $('form#user_delete button').click();
                layer.close(index);
            },
        })
    }
</script>
{% endif %}