article/urls.py
# 简单来说就是Model存取数据，View决定需要调取哪些数据，而Template则负责将调取出的数据以合理的方式展现出来。

# 引入path
from django.urls import path
from article import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 安全删除文章
    # path('article-delete/<int:id>', views.article_delete, name='article_delete'),
    path('article-safe-delete/<int:id>', views.article_safe_delete, name='article_safe_delete'),
    # 更新文章
    path('article-updatee/<int:id>/', views.article_updatee, name='article_updatee'),
    #类视图新建文章
    path('create-view/', views.ArticleCreateView.as_view(), name='...'),
    #点赞 +1
    path('increase-likes/<int:id>', views.IncreaseLikesView.as_view(), name='increase_likes'),

]

comment/urls.py
#! usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2022/1/4 10:45
# @Author: wangjunjie
# @File: urls.py
# @Des:

from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
#记得引入include
from django.urls import path, include
import notifications.urls

from article.views import article_list

urlpatterns = [
    path('admin/', admin.site.urls),

    #新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    #用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    #第三方库：密码重置
    path('password-reset/', include('password_reset.urls')),
    #评论
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('accounts/', include('allauth.urls')),
    #home
    path('', article_list, name='home'),
]

#添加这行
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
#! usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2021/12/29 17:29
# @Author: wangjunjie
# @File: urls.py
# @Des:

from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    #用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
# 导入内建的User模型
from django.contrib.auth.models import User
# timezone用于处理时间相关事务
from django.urls import reverse
from django.utils import timezone
# Django-taggit
from taggit.managers import TaggableManager
from PIL import Image

class ArticleColumn(models.Model):
    """栏目的Model"""
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)
    #保存时处理图片
    def save(self, *args, **kwargs):
        #调用原有的save()的功能
        article = super(ArticlePost, self).save(*args, **kwargs)
        #固定宽度缩放图片大小
        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)
        return article
    # 文章标签
    tags = TaggableManager(blank=True)
    # 文章作者。参数on_delete用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题。models.CharField为字符串字段，用于保存较短的字符串，比如标题
    title = models.CharField(max_length=100)

    # 文章正文。保存大量文本使用 TextField
    body = models.TextField()

    # 文章创建时间。参数default=timezone.now指定其在创建数据时默认写入当前的时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。参数auto_now=True指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # 浏览量
    total_views = models.PositiveIntegerField(default=0)

    #新增点赞数统计
    likes = models.PositiveIntegerField(default=0)

    # 文章栏目的“一对多”外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    # 内部类class Meta用于给model定义元数据
    class Meta:
        # ordering指定模型返回的数据的排列顺序
        # '-created'表明数据应该以倒序排列
        ordering = ('-created',)  # 元组

    # 函数 __str__定义当调用对象的str()方法时的返回值内容
    def __str__(self):
        # return self.title将文章标题返回
        return self.title

    def get_absolute_url(self):
        """获取文章地址"""
        return reverse('article:article_detail', args=[self.id])

article/forms.py
#! usr/bin/python3
# -*- coding:utf-8 -*-
# @Time: 2021/12/28 16:24
# @Author: wangjunjie
# @File: forms.py
# @Des:

from django import forms
from .models import ArticlePost


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body', 'tags', 'avatar')

article/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.views.generic import CreateView
# from comment.forms import CommentForm
# from comment.models import Comment
from comment.models import Comment
from .forms import ArticlePostForm
from .models import ArticlePost, ArticleColumn
from django.db.models import Q
import markdown


class ArticleCreateView(CreateView):
    """类视图新建文章"""
    model = ArticlePost

    fields = '__all__'
    template_name = 'article/create_by_class_view.html'


# 视图函数
def article_list(request):
    # 取出所有博客文章
    # 从url中提取查询参数
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # 初始化查询集
    article_list = ArticlePost.objects.all()

    # 搜索查询集
    if search:
        # 用Q对象进行联合搜索
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search = ''

    # 栏目查询集
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # 标签查询集
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # 查询集排序
    if order == 'total_views':
        article_list = article_list.order_by('-total_views')

    # 每页显示3篇文章
    paginator = Paginator(article_list, 3)
    # 获取url中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给articles
    articles = paginator.get_page(page)

    # 需要传递给模板（templates）的对象
    context = {'articles': articles,
               'order': order,
               'search': search,
               'column': column,
               'tag': tag, }
    # render函数：载入模板，并返回contenxt对象
    return render(request, 'article/list.html', context)


# 文章详情
def article_detail(request, id):
    # 取出相应的文章
    article = get_object_or_404(ArticlePost, id=id)
    # 浏览量+1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    # 修改markdown语法渲染
    md = markdown.Markdown(
        extensions=[
            # 包含缩写、表哥等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录扩展
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)
    # 取出文章评论
    comments = Comment.objects.filter(article=id)

    # 新增了md.toc对象
    context = {'article': article, 'toc': md.toc,'comments': comments }
    # 载入模板，并返回contenxt对象
    return render(request, 'article/detail.html', context)


# 写文章的视图
@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中id=1的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 指定目前登录的用户为作者
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            # 将新文章保存到数据库中
            new_article.save()
            # 新增代码，保存tags的多对多关系
            article_post_form.save_m2m()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 新增栏目
        columns = ArticleColumn.objects.all()
        # 赋值上下文
        context = {'article_post_form': article_post_form, 'columns': columns}
        # 返回模板
        return render(request, 'article/create.html', context)


# 删文章
# def article_delete(request, id):
#     # 根据id获取需要删除的文章
#     article = ArticlePost.objects.get(id=id)
#     # 调用delete()方法删除文章
#     article.delete()
#     # 完成删除后返回文章列表
#     return redirect("article:article_list")

# 安全删除文章
@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        # 过滤非作者的用户
        if request.user != article.author:
            return HttpResponse("抱歉，你无权删除这篇文章。")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")


# 更新文章
@login_required(login_url='/userprofile/login/')
def article_updatee(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id: 文章的id
    """
    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    # 判断用户是否为POST提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的title、body数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')
            article.tags.set(*request.POST.get('tags').split(','), clear=True)

            # 新增的代码
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的id值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 新增及修改的代码
        columns = ArticleColumn.objects.all
        # 赋值上下文，将article文章对象也传递进去，以便提取旧的内容
        context = {'article': article, 'article_post_form': article_post_form,
                   'columns': columns,
                   'tags': ','.join([x for x in article.tags.names()]), }
        # 将响应返回到模板中
        return render(request, 'article/updatee.html', context)

class IncreaseLikesView(View):
    """点赞数+1"""
    def post(self, request, *args, **kwargs):
        article = ArticlePost.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')

templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text"
                               class="form-control col-3"
                               id="tags"
                               name="tags"
                        >
                    </div>
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control"
                            id="column"
                            name="column"
                    >
                        <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                        <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/create_by_class_view.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入base.html中定义的title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入base.html中定义的content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 将原有内容嵌套进新的div中 -->
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">作者：{{ article.author }}
                {% if user == article.author %}
                <!-- 通过onclick实现了功能逻辑，因此href链接就不需要再跳转了 -->
                <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                <a href="{% url 'article:article_updatee' article.id %}">编辑文章</a>
                {% endif %}
                <!-- 新增一个隐藏的表单 -->
                <form
                        style="display:none;"
                        id="safe_delete"
                        action="{% url 'article:article_safe_delete' article.id %}"
                        method="POST"
                >
                    {% csrf_token %}
                    <button type="submit">发送</button>
                </form>
                <div>
                    浏览：{{ article.total_views }}
                </div>
            </div>


            <!-- 文章正文 -->
            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>

            <!-- 新增点赞按钮 -->
            <div style="text-align: center;" class="mt-4">
                <button class="btn btn-outline-danger"
                        type="button"
                        onclick="validate_is_like(
                            '{% url 'article:increase_likes' article.id %}',
                            {{ article.id }},
                            {{ article.likes }}
                            )"
                        >
                    <span>点赞</span>
                    <span>
                        <i class="fas fa-heart"></i>
                    </span>
                    <span id="likes_number">
                        {{ article.likes }}
                    </span>
                </button>
            </div>

            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form
                        action="{% url 'comment:post_comment' article.id %}"
                        method="POST"
                    >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    我也要发言：
                                </strong>
                            </label>
                            <!-- 将之前的<textarea>替换掉 -->
                            <!-- <textarea
                                type="text"
                                class="form-control"
                                id="body"
                                name="body"
                                rows="2"></textarea> -->
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}
            <!-- 改动 显示评论 部分 -->
            {% load mptt_tags %}
            <h4>共有{{ comments.count }}条评论</h4>
            <div class="row">
                <!-- 遍历树形结构 -->
                {% recursetree comments %}
                    <!-- 给node取个别名comment -->
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif%}"
                        >
                            <hr>
                            <p>
                                <strong style="color: pink">
                                    {{ comment.user }}
                                </strong>

                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right"
                                       style="color: cornflowerblue;"
                                    ></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong>
                                {% endif %}
                            </p>
                            <div>{{ comment.body|safe }}</div>
                            <div>
                                <span style="color: gray">
                                    {{ comment.created|date:"Y-m-d H:i" }}
                                </span>

                                <!-- 加载modal的按钮 -->
                                {% if user.is_authenticated %}
                                <button type="button"
                                        class="btn btn-light btn-sm text-muted"
                                        onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                >
                                    回复
                                </button>
                                {% else %}
                                <a class="btn btn-light btn-sm text-muted"
                                   href="{% url 'userprofile:login' %}"
                                >
                                    回复
                                </a>
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade"
                                 id="comment_{{ comment.id }}"
                                 tabindex="-1"
                                 role="dialog"
                                 aria-labelledby="CommentModalCenter"
                                 aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}: </h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>

                    {% endwith %}
                {% endrecursetree %}
            </div>
            <div>
                {% for comment in comments %}
                    <hr>
                    <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong> 于
                        <span style="color: green">
                            {{ comment.created|date:"Y-m-d H:i:s" }}
                        </span>时说：
                    </p>
                    <div>{{ comment.body|safe }}</div>
                {% endfor %}
            </div>
        </div>
        <!-- 新增的目录 -->
        <div id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    //删除文章的函数
    function confirm_safe_delete() {
        //调用layer弹窗组件
        layer.open({
            //弹窗标题
            title: "确认删除",
            //正文
            content: "确认删除这篇文章吗？",
            //点击确定按钮后调用的回调函数
            yes: function (index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            },
        })
    }
</script>

<!-- 粘性侧边栏样式 -->
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0,0);
        transform: translate3d(0,0,0);
        will-change: position, transform;
    }
</style>
<!-- 新增代码 -->
{% block script %}
<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>
<!-- 引入粘性侧边栏 -->
<script src="{% static 'sticky-sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    })
</script>

<!-- 新增代码，唤醒二级回复的modal -->
<script>
    //加载modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        //加载编辑器
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' +
                article_id +
                '/' +
                comment_id +
                '"' +
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                comment_id +
                '"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    }
</script>

<!-- 以下均为新代码 -->
<!-- csrf token -->
<script src="{% static 'csrf.js' %}"></script>
<script>
    //点赞功能主函数
    function validate_is_like(url, id, likes) {
        //取出LocalStorage中的数据
        let storage = window.localStorage;
        const storage_str_data = storage.getItem("my_blog_data");
        let storage_json_data = JSON.parse(storage_str_data);
        //若数据不存在，则创建空字典
        if (!storage_json_data) {
            storage_json_data = {}
        };
        //检查当前文章是否已点赞。是则 status = true
        const status = check_status(storage_json_data, id);
        if (status) {
            layer.msg('已经点过赞了哟~');
            //点过赞则立即退出函数
            return;
        } else {
            //用Jquery找到点赞数量，并+1
            $('span#likes_number').text(likes + 1).css('color', '#dc3545');
        }
        //用ajax向后端发送post请求
        $.post(
            url,
            //post只是为了做csrf校验，因此数据为空
            {},
            function (result) {
                if (result === 'success') {
                    //尝试修改点赞数据
                    try {
                        storage_json_data[id] = true;
                    } catch (e) {
                        window.localStorage.clear();
                    };
                    //将字典转换为字符串，以便存储到LocalStorage
                    const d = JSON.stringify(storage_json_data);
                    //尝试存储点赞数据到LocalStorage
                    try {
                        storage.setItem("my_blog_data", d);
                    } catch (e) {
                        //code 22错误表示LocalStorage空间满了
                        if (e.code === 22) {
                            window.localStorage.clear();
                            storage.setItem("my_blog_data", d);
                        }
                    };
                } else {
                    layer.msg("与服务器通信失败..过一会儿再试试呗~");
                }
            }
        );
    };

    //辅助点赞主函数，验证点赞状态
    function check_status(data, id) {
        //尝试查询点赞状态
        try {
            if (id in data && data[id]) {
                return true;
            } else {
                return false;
            }
        } catch (e) {
            window.localStorage.clear();
            return false;
        };
    };
</script>
{% endblock script %}
{% endblock content %}

templates/article/updatee.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <!-- 文章标题图 -->
                <div class="form-group">
                    <label for="avatar">标题图</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>
                <!-- 文章标签 -->
                <div class="form-group">
                    <label for="tags">标签</label>
                    <input type="text" class="form-control col-3" id="tags" name="tags">
                        value="{{ tags }}"
                </div>
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在value属性中指定文本框的初始值为旧的内容，即article对象中的title字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title}}">
                </div>
                <!-- 文章栏目 -->
                <div class="form-group">
                    <label for="column">栏目</label>
                    <select class="form-control"
                            id="column"
                            name="column"
                    >
                            <option value="none">请选择栏目..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                    {% if column.id == article.column.id %}
                                        selected
                                    {% endif %}
                            >
                                    {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要value属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}